language: scala
sudo: true
dist: trusty

services:
  - docker

before_install:
  # make comparing to origin/master work
  - git remote set-branches --add origin master && git fetch
  # fetch full history for correct current and previous version detection
  - git fetch --unshallow
  # using jabba for custom jdk management
  - if [ ! -f ~/.jabba/jabba.sh ]; then curl -L -v --retry 5 -o jabba-install.sh https://raw.githubusercontent.com/shyiko/jabba/0.11.2/install.sh && bash jabba-install.sh; fi
  - . ~/.jabba/jabba.sh
  - jabba install adopt@~1.8-0
  - jabba install adopt@~1.11-0

before_script:
  - unset _JAVA_OPTIONS

jobs:
  include:
    - stage: check
      script: sbt -jvm-opts .jvmopts-travis verifyCodeStyle
      name: "Code style check. Run locally with: sbt verifyCodeStyle"
    - script: sbt -jvm-opts .jvmopts-travis ++2.13.1 Test/compile
      name: Compile all tests (with Scala 2.13)
    - script: sbt -jvm-opts .jvmopts-travis unidoc
      name: Create all API docs
    - script: sbt -jvm-opts .jvmopts-travis docs/paradox
      name: Create site with Paradox

    - stage: test
      script: jabba use adopt@~1.8-0 && java -version && docker-compose up -d cassandra && sbt -jvm-opts .jvmopts-travis +test
      name: Run all tests with Jdk 8
    - script: jabba use adopt@~1.11-0 && java -version && docker-compose up -d cassandra && sbt -jvm-opts .jvmopts-travis +test
      name: Run all tests with Jdk 11
    - script: jabba use adopt@~1.11-0 && java -version && docker-compose up -d cassandra && ./testLatestAkkaSnapshot.sh
      name: "Run against latest Akka snapshot"
      if: type = cron
    - script: jabba use adopt@~1.11-0 && java -version && docker-compose up -d cassandra2 && sbt -jvm-opts .jvmopts-travis "testOnly -- -l RequiresCassandraThree"
      name: "Run against Cassandra 2.2"
      if: type = cron

    - stage: whitesource
      name: White Source
      script: git branch -f "$TRAVIS_BRANCH" && git checkout "$TRAVIS_BRANCH" && sbt -jvm-opts .jvmopts-travis whitesourceCheckPolicies whitesourceUpdate

    - stage: publish
      script: openssl aes-256-cbc -K $encrypted_fb56f898a62a_key -iv $encrypted_fb56f898a62a_iv -in .travis/sign_key.enc -out sign_key -d && gpg --import sign_key && sbt -jvm-opts .jvmopts-travis +publish
      name: Publish artifacts

    - script: eval "$(ssh-agent -s)" && cp .travis/id_rsa /tmp/id_rsa && chmod 600 /tmp/id_rsa && ssh-keygen -p -P "$DEPLOY_PASSPHRASE" -N "" -f /tmp/id_rsa && ssh-add /tmp/id_rsa && sbt -jvm-opts .jvmopts-travis docs/publishRsync
      name: Publish documentation

stages:
  # runs on master commits and PRs
  - name: check
    if: NOT tag =~ ^v

  # runs on master commits and PRs
  - name: test
    if: NOT tag =~ ^v

  # runs on main repo master commits or version-tagged commits
  - name: whitesource
    if: repo = akka/akka-persistence-cassandra AND ( ( branch = master AND type = push ) OR tag =~ ^v )

  # runs on main repo master commits or version-tagged commits
  - name: publish
    if: repo = akka/akka-persistence-cassandra AND ( ( branch = master AND type = push ) OR tag =~ ^v )


after_failure:
  - docker-compose logs

before_cache:
  - find $HOME/.ivy2/ -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt   -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.jabba

env:
  global:
    # encrypt with: travis encrypt WHITESOURCE_PASSWORD=...
    - secure: "IzUV1Al/h67Zl4cZZtfgYayR7JTfMU34vWkxHqzrYCE3HOVgLRNwMgXirDMbKwnbUlH7HKZFnxPzlySEJ3bi2bh+R/yfOzjWntaxHNLxv2S1sbt5182RrPEPs89jYxKltGGaJ14j8cJ/RJjVau3wsSnHsTz6k1FaSh0eZ/l4Kn576bj5hkgWJKIEDhhsGPzlq1YPp4gUwAHWNb9C85aN2AiBnuNRW5Qup8ZrNUJUGOX3QJD4wTF41mhh5itX6as1xRgmEjmf0Xf4BeLkseaCfkVc4+A79Svs/bM77MXBkbSbEoljDsgl+z+56rUm4PNxP/4LPGW5Kh9IKe6edw8HzSSOoUkX2Xh8rYTdiC8ZtGnfIHNqUrStD90T08cV4/yutohUUVrBx0kNiX2M1NKIYTQS6G+9z5vEJqpytxflsnXlP8ZgvPQJIKzksT69QkXssh550fpdUZ+tuuDIYieaS2/e53ypL1QUUFnOv6f9wbCY8lHRXQj7KAtdGa2aBJ6+WM2Rlx2zVOL2xhf3ZhP1RpoMRxsa2KTn9ysg4yzQelK51nHdzavyJluF1YU8j5gQ3xyg3a7gmjo61alGVyV5V6yNSU603JMWmOwRinDxJ1XiIgLjal31A5UYK47RorWTw22gpyW7IbNv4/RmltuABaDMbYZLBFQmOh2oiyDAgxc="
    # encrypt with: travis encrypt DEPLOY_PASSPHRASE=...
    - secure: "IR3ZIjIkntpUkdpDJucegjzBN2QsaOKhGhph9dV7ZCtt9RUpbaTgjZZNuFpY7ss5aIJid2JgRvV8Vip6HhRErPertI9nMwbpsBNwdAt3QcqA2oVe3XERANIaEqA5JcWyW1uvJDShnR0KjX4eBDqMBZH36oZiATnW1nrsuMgsdzS8BBC4WCyPRsxmE9gMsnVXNproUGPauytcgtZooFGV1D94r0dKWcGw9ROVQ9WF+LsdrK3Mqkv4pEH5l+WIGWM1gCFFP73v/uaK407mCDKBgQPbUHt+SMOC1tRqS5arp/fxmKEhCV7oEGQzPmVcy+lVRC9NEf2biHMaWmbwNsYLNxV+FBGvLOYAY346q/S+dXZCaSmsEx3K+oEUlrr9UdSkUGWRjNWH0R/Gogyp3rPtemqJduGL3k5IbkPwF9xiq+PjCI9a3fc8LJhbnD53xDe/FsZjg2THf9A1DaTYFPWXmNMfHG0fgTIPsVAMnRGszk/HoyvvIh+aRh5y1uC0GMSZFzLX50tSGr4dsZ0C+fXA8sdZXBAJKdXtuXp/Y7CNMNo1eKKLBW+Vh1Cb/9wTMSaxnhENgIocHgEqeFct2aaUBRy+Dri3zA5L+sUwBJvyNrhuk+nIylqoMPlbPxFnZv9hHyJakIL/YfGzSVYjWiYco83Ot60VqmdJW0ZNoXjR2Zw="
    # encrypt with: travis encrypt BINTRAY_USER=...
    - secure: "pjOz1s3okEcaN/XmLg/gsvENF4EsxJxWs+Ac8wUxcU+mYcn75JTKEs5UC5sfUCsBDpDeFpGrDwarrbD3Adyc3eP9m7IiP9rcDuqrWaWhpQci1a/ixzgJYluwVc0iTv/OzWJPy97sJ3rPsTLD6wOTghz2x82LnkABYnRm2eseXuxCIIINOt97EJs0bgbnu/grRWcdlHgKj+0RJUvSgDtZgI5+yUmof/xhzMQ9ogXIQUzu6sBvPj8b9eOePRgDRLFpezrrzWYovE27E8NNHdCl24UYsTBCahYlcLAuRf0W7AgI4Tj+frMdydgAeObkjX4FCWZIhyNG2GVc8x/lVyYwCcg1ZH4Zym1qHfdREOfTKB8ypmvgZGBQaq/aKTNLNDCIbuAFt9nAwcD6Ziu612MqSVAZW/E0m36b8Z3M2gkbW2pHZiLh5qi97KTUehKZCu/C59grZEjpjd8Dm92D8O4l+G4aWKRWOOAyyqh7j+pI9ZOq4sm2q7ycH1DgOyReUh5MS1q93kf8aPUKw27SEF2KQ7Xm9+T4Zmj6L9QTrMDzeRFhRVrwOuuSvWPEFBcVgzYTZ3Zz9w6IIJX8v/RGPXqu4DyweZCRDT65CwrvcQTvrh9cs+lcHHtuDCvtTpsFHIHvN4gDs/eC+kIIchVIsRE94BHzS7UFg22ZPXW2WXDo90M="
    # encrypt with: travis encrypt BINTRAY_PASS=...
    - secure: "i8g1W7Fqbh9XkkpmZuhQy6862z7fzGrPAKZFiQB/xvCXKofRPvESrj89YhG1r5ifj5/hgeNe77JIbELyrU2Nk8Xot1c8LusqO9tujmJcD2+V/Huxn07CGNCHngcsG+7DRNwsYypm+DMSaxy+cxdFMcPG4EryRVaoRd0wRcPS6Xfns0zngqCMb7BJThC5e/GPM3pW6jgwsP7IW+9n7MiHzUAwI172auiYgNYOT6EgjXS+Yj6mEr0meka6IMeM7CQMipeQCD0NpFnmjEp8OguBcyyty8Ovf1BoPQwt+KYtv3jEAWfc6enBULr1DjrKMQiOeig18/MPRgTJP7Po7n6sQgvovn3BqxffOgFY/+IMLeB7gT6bvBCzm1vN5xx+nXf/EXhBEUYYnBXbtj2XKqi47MLuLtju9fAmlooy6iTmnSrmQlaJI12OjLo6vx26Q0UWnHeGlj7iro+254mKv02HiuXu1WqBwcA9E+lFkTT9vF0xx0uhzBclKbfgHJLfnsylMAQ5KwvX8re1RN9QISUJzLIuLfnWLex9ATzL7WoJcolyTONEk9+Pszxi8AlIvo2tJSWiKYrkKgRgYMrFwUxfHvPN7HddCZl37sykkY1XmVeXj2s3tnqAYtZdYx8KVezIuAxD75ph6dfToCvoe2qr3fcOfyQAFnR3YVfMk6miShQ="

# safelist
branches:
  only:
    - master
    - release-0.x
    - release-0.50
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
